version: "3.7"

services:
  redis:
    image: redis
    command: ["redis-server",  "--requirepass", "password"]
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./keys/jwks.json:/usr/share/nginx/html/.well-known/jwks.json
  keto:
    image: oryd/keto:v0.8.0-alpha.2
    ports:
      - '4466:4466'
      - '4467:4467'
    restart: on-failure
    links:
      - postgresd:postgresd
    depends_on:
      - keto-migrate
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - DSN=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
  keto-migrate:
    image: oryd/keto:v0.8.0-alpha.2
    links:
      - postgresd:postgresd
    volumes:
      - type: bind
        source: ./config
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    command: ['migrate', 'up', '-y']
    restart: on-failure
  postgresd:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb
