version: "3.7"

services:
  redis:
    image: redis
    command: ["redis-server",  "--requirepass", "password"]
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./keys/jwks.json:/usr/share/nginx/html/.well-known/jwks.json
  spicedb:
    image: authzed/spicedb:v1.8.0
    ports:
      - "50051:50051"
    command: serve --grpc-preshared-key "somerandomkeyhere"
