{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "chart.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "chart.fullname" . }}
        subset: stable  # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
      weight: 100
    - destination:
        host: {{ include "chart.fullname" . }}
        subset: canary  # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  host: {{ include "chart.fullname" . }}
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels: {}       # labels will be injected with canary rollouts-pod-template-hash value
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels: {}     # labels will be injected with stable rollouts-pod-template-hash value
{{- end }}