# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ory/keto/acl/v1alpha1/check_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from counter_app.ory.keto.acl.v1alpha1 import (
    acl_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_acl__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n)ory/keto/acl/v1alpha1/check_service.proto\x12\x15ory.keto.acl.v1alpha1\x1a\x1fory/keto/acl/v1alpha1/acl.proto"\xaa\x01\n\x0c\x43heckRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x10\n\x08relation\x18\x03 \x01(\t\x12/\n\x07subject\x18\x04 \x01(\x0b\x32\x1e.ory.keto.acl.v1alpha1.Subject\x12\x0e\n\x06latest\x18\x05 \x01(\x08\x12\x11\n\tsnaptoken\x18\x06 \x01(\t\x12\x11\n\tmax_depth\x18\x07 \x01(\x05"3\n\rCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x11\n\tsnaptoken\x18\x02 \x01(\t2b\n\x0c\x43heckService\x12R\n\x05\x43heck\x12#.ory.keto.acl.v1alpha1.CheckRequest\x1a$.ory.keto.acl.v1alpha1.CheckResponseB\x94\x01\n\x18sh.ory.keto.acl.v1alpha1B\x11\x43heckServiceProtoP\x01Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\xaa\x02\x15Ory.Keto.Acl.V1Alpha1\xca\x02\x15Ory\\Keto\\Acl\\V1alpha1b\x06proto3'
)


_CHECKREQUEST = DESCRIPTOR.message_types_by_name["CheckRequest"]
_CHECKRESPONSE = DESCRIPTOR.message_types_by_name["CheckResponse"]
CheckRequest = _reflection.GeneratedProtocolMessageType(
    "CheckRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECKREQUEST,
        "__module__": "ory.keto.acl.v1alpha1.check_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.CheckRequest)
    },
)
_sym_db.RegisterMessage(CheckRequest)

CheckResponse = _reflection.GeneratedProtocolMessageType(
    "CheckResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECKRESPONSE,
        "__module__": "ory.keto.acl.v1alpha1.check_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.CheckResponse)
    },
)
_sym_db.RegisterMessage(CheckResponse)

_CHECKSERVICE = DESCRIPTOR.services_by_name["CheckService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030sh.ory.keto.acl.v1alpha1B\021CheckServiceProtoP\001Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\252\002\025Ory.Keto.Acl.V1Alpha1\312\002\025Ory\\Keto\\Acl\\V1alpha1"
    _CHECKREQUEST._serialized_start = 102
    _CHECKREQUEST._serialized_end = 272
    _CHECKRESPONSE._serialized_start = 274
    _CHECKRESPONSE._serialized_end = 325
    _CHECKSERVICE._serialized_start = 327
    _CHECKSERVICE._serialized_end = 425
# @@protoc_insertion_point(module_scope)
