# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ory/keto/acl/v1alpha1/expand_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ory.keto.acl.v1alpha1 import (
    acl_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_acl__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*ory/keto/acl/v1alpha1/expand_service.proto\x12\x15ory.keto.acl.v1alpha1\x1a\x1fory/keto/acl/v1alpha1/acl.proto"f\n\rExpandRequest\x12/\n\x07subject\x18\x01 \x01(\x0b\x32\x1e.ory.keto.acl.v1alpha1.Subject\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\x12\x11\n\tsnaptoken\x18\x03 \x01(\t"B\n\x0e\x45xpandResponse\x12\x30\n\x04tree\x18\x01 \x01(\x0b\x32".ory.keto.acl.v1alpha1.SubjectTree"\xa8\x01\n\x0bSubjectTree\x12\x32\n\tnode_type\x18\x01 \x01(\x0e\x32\x1f.ory.keto.acl.v1alpha1.NodeType\x12/\n\x07subject\x18\x02 \x01(\x0b\x32\x1e.ory.keto.acl.v1alpha1.Subject\x12\x34\n\x08\x63hildren\x18\x03 \x03(\x0b\x32".ory.keto.acl.v1alpha1.SubjectTree*\x83\x01\n\x08NodeType\x12\x19\n\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fNODE_TYPE_UNION\x10\x01\x12\x17\n\x13NODE_TYPE_EXCLUSION\x10\x02\x12\x1a\n\x16NODE_TYPE_INTERSECTION\x10\x03\x12\x12\n\x0eNODE_TYPE_LEAF\x10\x04\x32\x66\n\rExpandService\x12U\n\x06\x45xpand\x12$.ory.keto.acl.v1alpha1.ExpandRequest\x1a%.ory.keto.acl.v1alpha1.ExpandResponseB\x95\x01\n\x18sh.ory.keto.acl.v1alpha1B\x12\x45xpandServiceProtoP\x01Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\xaa\x02\x15Ory.Keto.Acl.V1Alpha1\xca\x02\x15Ory\\Keto\\Acl\\V1alpha1b\x06proto3'
)

_NODETYPE = DESCRIPTOR.enum_types_by_name["NodeType"]
NodeType = enum_type_wrapper.EnumTypeWrapper(_NODETYPE)
NODE_TYPE_UNSPECIFIED = 0
NODE_TYPE_UNION = 1
NODE_TYPE_EXCLUSION = 2
NODE_TYPE_INTERSECTION = 3
NODE_TYPE_LEAF = 4


_EXPANDREQUEST = DESCRIPTOR.message_types_by_name["ExpandRequest"]
_EXPANDRESPONSE = DESCRIPTOR.message_types_by_name["ExpandResponse"]
_SUBJECTTREE = DESCRIPTOR.message_types_by_name["SubjectTree"]
ExpandRequest = _reflection.GeneratedProtocolMessageType(
    "ExpandRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _EXPANDREQUEST,
        "__module__": "ory.keto.acl.v1alpha1.expand_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.ExpandRequest)
    },
)
_sym_db.RegisterMessage(ExpandRequest)

ExpandResponse = _reflection.GeneratedProtocolMessageType(
    "ExpandResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _EXPANDRESPONSE,
        "__module__": "ory.keto.acl.v1alpha1.expand_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.ExpandResponse)
    },
)
_sym_db.RegisterMessage(ExpandResponse)

SubjectTree = _reflection.GeneratedProtocolMessageType(
    "SubjectTree",
    (_message.Message,),
    {
        "DESCRIPTOR": _SUBJECTTREE,
        "__module__": "ory.keto.acl.v1alpha1.expand_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.SubjectTree)
    },
)
_sym_db.RegisterMessage(SubjectTree)

_EXPANDSERVICE = DESCRIPTOR.services_by_name["ExpandService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030sh.ory.keto.acl.v1alpha1B\022ExpandServiceProtoP\001Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\252\002\025Ory.Keto.Acl.V1Alpha1\312\002\025Ory\\Keto\\Acl\\V1alpha1"
    _NODETYPE._serialized_start = 446
    _NODETYPE._serialized_end = 577
    _EXPANDREQUEST._serialized_start = 102
    _EXPANDREQUEST._serialized_end = 204
    _EXPANDRESPONSE._serialized_start = 206
    _EXPANDRESPONSE._serialized_end = 272
    _SUBJECTTREE._serialized_start = 275
    _SUBJECTTREE._serialized_end = 443
    _EXPANDSERVICE._serialized_start = 579
    _EXPANDSERVICE._serialized_end = 681
# @@protoc_insertion_point(module_scope)
