# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ory.keto.acl.v1alpha1 import (
    expand_service_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2,
)


class ExpandServiceStub(object):
    """The service that performs subject set expansion
    based on the stored Access Control Lists.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Expand = channel.unary_unary(
            "/ory.keto.acl.v1alpha1.ExpandService/Expand",
            request_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandRequest.SerializeToString,
            response_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandResponse.FromString,
        )


class ExpandServiceServicer(object):
    """The service that performs subject set expansion
    based on the stored Access Control Lists.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    def Expand(self, request, context):
        """Expands the subject set into a tree of subjects."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExpandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Expand": grpc.unary_unary_rpc_method_handler(
            servicer.Expand,
            request_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandRequest.FromString,
            response_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ory.keto.acl.v1alpha1.ExpandService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ExpandService(object):
    """The service that performs subject set expansion
    based on the stored Access Control Lists.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    @staticmethod
    def Expand(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ory.keto.acl.v1alpha1.ExpandService/Expand",
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandRequest.SerializeToString,
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_expand__service__pb2.ExpandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
