# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ory/keto/acl/v1alpha1/read_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ory.keto.acl.v1alpha1 import (
    acl_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_acl__pb2,
)
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(ory/keto/acl/v1alpha1/read_service.proto\x12\x15ory.keto.acl.v1alpha1\x1a\x1fory/keto/acl/v1alpha1/acl.proto\x1a google/protobuf/field_mask.proto"\xbc\x02\n\x19ListRelationTuplesRequest\x12\x45\n\x05query\x18\x01 \x01(\x0b\x32\x36.ory.keto.acl.v1alpha1.ListRelationTuplesRequest.Query\x12/\n\x0b\x65xpand_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\x12\x11\n\tsnaptoken\x18\x03 \x01(\t\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x12\n\npage_token\x18\x05 \x01(\t\x1am\n\x05Query\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x10\n\x08relation\x18\x03 \x01(\t\x12/\n\x07subject\x18\x04 \x01(\x0b\x32\x1e.ory.keto.acl.v1alpha1.Subject"t\n\x1aListRelationTuplesResponse\x12=\n\x0frelation_tuples\x18\x01 \x03(\x0b\x32$.ory.keto.acl.v1alpha1.RelationTuple\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\x88\x01\n\x0bReadService\x12y\n\x12ListRelationTuples\x12\x30.ory.keto.acl.v1alpha1.ListRelationTuplesRequest\x1a\x31.ory.keto.acl.v1alpha1.ListRelationTuplesResponseB\x93\x01\n\x18sh.ory.keto.acl.v1alpha1B\x10ReadServiceProtoP\x01Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\xaa\x02\x15Ory.Keto.Acl.V1Alpha1\xca\x02\x15Ory\\Keto\\Acl\\V1alpha1b\x06proto3'
)


_LISTRELATIONTUPLESREQUEST = DESCRIPTOR.message_types_by_name[
    "ListRelationTuplesRequest"
]
_LISTRELATIONTUPLESREQUEST_QUERY = _LISTRELATIONTUPLESREQUEST.nested_types_by_name[
    "Query"
]
_LISTRELATIONTUPLESRESPONSE = DESCRIPTOR.message_types_by_name[
    "ListRelationTuplesResponse"
]
ListRelationTuplesRequest = _reflection.GeneratedProtocolMessageType(
    "ListRelationTuplesRequest",
    (_message.Message,),
    {
        "Query": _reflection.GeneratedProtocolMessageType(
            "Query",
            (_message.Message,),
            {
                "DESCRIPTOR": _LISTRELATIONTUPLESREQUEST_QUERY,
                "__module__": "ory.keto.acl.v1alpha1.read_service_pb2"
                # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.ListRelationTuplesRequest.Query)
            },
        ),
        "DESCRIPTOR": _LISTRELATIONTUPLESREQUEST,
        "__module__": "ory.keto.acl.v1alpha1.read_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.ListRelationTuplesRequest)
    },
)
_sym_db.RegisterMessage(ListRelationTuplesRequest)
_sym_db.RegisterMessage(ListRelationTuplesRequest.Query)

ListRelationTuplesResponse = _reflection.GeneratedProtocolMessageType(
    "ListRelationTuplesResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LISTRELATIONTUPLESRESPONSE,
        "__module__": "ory.keto.acl.v1alpha1.read_service_pb2"
        # @@protoc_insertion_point(class_scope:ory.keto.acl.v1alpha1.ListRelationTuplesResponse)
    },
)
_sym_db.RegisterMessage(ListRelationTuplesResponse)

_READSERVICE = DESCRIPTOR.services_by_name["ReadService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030sh.ory.keto.acl.v1alpha1B\020ReadServiceProtoP\001Z3github.com/ory/keto/proto/ory/keto/acl/v1alpha1;acl\252\002\025Ory.Keto.Acl.V1Alpha1\312\002\025Ory\\Keto\\Acl\\V1alpha1"
    _LISTRELATIONTUPLESREQUEST._serialized_start = 135
    _LISTRELATIONTUPLESREQUEST._serialized_end = 451
    _LISTRELATIONTUPLESREQUEST_QUERY._serialized_start = 342
    _LISTRELATIONTUPLESREQUEST_QUERY._serialized_end = 451
    _LISTRELATIONTUPLESRESPONSE._serialized_start = 453
    _LISTRELATIONTUPLESRESPONSE._serialized_end = 569
    _READSERVICE._serialized_start = 572
    _READSERVICE._serialized_end = 708
# @@protoc_insertion_point(module_scope)
