# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from counter_app.ory.keto.acl.v1alpha1 import (
    read_service_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2,
)


class ReadServiceStub(object):
    """The service to query relation tuples.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRelationTuples = channel.unary_unary(
            "/ory.keto.acl.v1alpha1.ReadService/ListRelationTuples",
            request_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesRequest.SerializeToString,
            response_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesResponse.FromString,
        )


class ReadServiceServicer(object):
    """The service to query relation tuples.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    def ListRelationTuples(self, request, context):
        """Lists ACL relation tuples."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ReadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListRelationTuples": grpc.unary_unary_rpc_method_handler(
            servicer.ListRelationTuples,
            request_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesRequest.FromString,
            response_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ory.keto.acl.v1alpha1.ReadService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ReadService(object):
    """The service to query relation tuples.

    This service is part of the [read-APIs](../concepts/api-overview.mdx#read-apis).
    """

    @staticmethod
    def ListRelationTuples(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ory.keto.acl.v1alpha1.ReadService/ListRelationTuples",
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesRequest.SerializeToString,
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_read__service__pb2.ListRelationTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
