# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from counter_app.ory.keto.acl.v1alpha1 import (
    write_service_pb2 as ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2,
)


class WriteServiceStub(object):
    """The write service to create and delete Access Control Lists.

    This service is part of the [write-APIs](../concepts/api-overview.mdx#write-apis).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransactRelationTuples = channel.unary_unary(
            "/ory.keto.acl.v1alpha1.WriteService/TransactRelationTuples",
            request_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesRequest.SerializeToString,
            response_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesResponse.FromString,
        )
        self.DeleteRelationTuples = channel.unary_unary(
            "/ory.keto.acl.v1alpha1.WriteService/DeleteRelationTuples",
            request_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesRequest.SerializeToString,
            response_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesResponse.FromString,
        )


class WriteServiceServicer(object):
    """The write service to create and delete Access Control Lists.

    This service is part of the [write-APIs](../concepts/api-overview.mdx#write-apis).
    """

    def TransactRelationTuples(self, request, context):
        """Writes one or more relation tuples in a single transaction."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteRelationTuples(self, request, context):
        """Deletes relation tuples based on relation query"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WriteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TransactRelationTuples": grpc.unary_unary_rpc_method_handler(
            servicer.TransactRelationTuples,
            request_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesRequest.FromString,
            response_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesResponse.SerializeToString,
        ),
        "DeleteRelationTuples": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteRelationTuples,
            request_deserializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesRequest.FromString,
            response_serializer=ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ory.keto.acl.v1alpha1.WriteService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WriteService(object):
    """The write service to create and delete Access Control Lists.

    This service is part of the [write-APIs](../concepts/api-overview.mdx#write-apis).
    """

    @staticmethod
    def TransactRelationTuples(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ory.keto.acl.v1alpha1.WriteService/TransactRelationTuples",
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesRequest.SerializeToString,
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.TransactRelationTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteRelationTuples(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ory.keto.acl.v1alpha1.WriteService/DeleteRelationTuples",
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesRequest.SerializeToString,
            ory_dot_keto_dot_acl_dot_v1alpha1_dot_write__service__pb2.DeleteRelationTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
