"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import ory.keto.acl.v1alpha1.acl_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TransactRelationTuplesRequest(google.protobuf.message.Message):
    """The request of a WriteService.TransactRelationTuples RPC."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RELATION_TUPLE_DELTAS_FIELD_NUMBER: builtins.int
    @property
    def relation_tuple_deltas(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___RelationTupleDelta
    ]:
        """The write delta for the relation tuples operated in one single transaction.
        Either all actions succeed or no change takes effect on error.
        """
        pass
    def __init__(
        self,
        *,
        relation_tuple_deltas: typing.Optional[
            typing.Iterable[global___RelationTupleDelta]
        ] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "relation_tuple_deltas", b"relation_tuple_deltas"
        ],
    ) -> None: ...

global___TransactRelationTuplesRequest = TransactRelationTuplesRequest

class RelationTupleDelta(google.protobuf.message.Message):
    """Write-delta for a TransactRelationTuplesRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Action:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[
            RelationTupleDelta._Action.ValueType
        ],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTION_UNSPECIFIED: RelationTupleDelta._Action.ValueType  # 0
        """Unspecified.
        The `TransactRelationTuples` RPC ignores this
        RelationTupleDelta if an action was unspecified.
        """

        INSERT: RelationTupleDelta._Action.ValueType  # 1
        """Insertion of a new RelationTuple.
        It is ignored if already existing.
        """

        DELETE: RelationTupleDelta._Action.ValueType  # 2
        """Deletion of the RelationTuple.
        It is ignored if it does not exist.
        """

    class Action(_Action, metaclass=_ActionEnumTypeWrapper):
        pass
    ACTION_UNSPECIFIED: RelationTupleDelta.Action.ValueType  # 0
    """Unspecified.
    The `TransactRelationTuples` RPC ignores this
    RelationTupleDelta if an action was unspecified.
    """

    INSERT: RelationTupleDelta.Action.ValueType  # 1
    """Insertion of a new RelationTuple.
    It is ignored if already existing.
    """

    DELETE: RelationTupleDelta.Action.ValueType  # 2
    """Deletion of the RelationTuple.
    It is ignored if it does not exist.
    """

    ACTION_FIELD_NUMBER: builtins.int
    RELATION_TUPLE_FIELD_NUMBER: builtins.int
    action: global___RelationTupleDelta.Action.ValueType
    """The action to do on the RelationTuple."""

    @property
    def relation_tuple(self) -> ory.keto.acl.v1alpha1.acl_pb2.RelationTuple:
        """The target RelationTuple."""
        pass
    def __init__(
        self,
        *,
        action: global___RelationTupleDelta.Action.ValueType = ...,
        relation_tuple: typing.Optional[
            ory.keto.acl.v1alpha1.acl_pb2.RelationTuple
        ] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["relation_tuple", b"relation_tuple"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "action", b"action", "relation_tuple", b"relation_tuple"
        ],
    ) -> None: ...

global___RelationTupleDelta = RelationTupleDelta

class TransactRelationTuplesResponse(google.protobuf.message.Message):
    """The response of a WriteService.TransactRelationTuples rpc."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SNAPTOKENS_FIELD_NUMBER: builtins.int
    @property
    def snaptokens(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """This field is not implemented yet and has no effect.
        <!--
        The list of the new latest snapshot tokens of the affected RelationTuple,
        with the same index as specified in the `relation_tuple_deltas` field of
        the TransactRelationTuplesRequest request.

        If the RelationTupleDelta_Action was DELETE
        the snaptoken is empty at the same index.
        -->
        """
        pass
    def __init__(
        self,
        *,
        snaptokens: typing.Optional[typing.Iterable[typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["snaptokens", b"snaptokens"]
    ) -> None: ...

global___TransactRelationTuplesResponse = TransactRelationTuplesResponse

class DeleteRelationTuplesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Query(google.protobuf.message.Message):
        """The query for deleting relation tuples"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        NAMESPACE_FIELD_NUMBER: builtins.int
        OBJECT_FIELD_NUMBER: builtins.int
        RELATION_FIELD_NUMBER: builtins.int
        SUBJECT_FIELD_NUMBER: builtins.int
        namespace: typing.Text
        """Optional. The namespace to query."""

        object: typing.Text
        """Optional. The object to query for."""

        relation: typing.Text
        """Optional. The relation to query for."""

        @property
        def subject(self) -> ory.keto.acl.v1alpha1.acl_pb2.Subject:
            """Optional. The subject to query for."""
            pass
        def __init__(
            self,
            *,
            namespace: typing.Text = ...,
            object: typing.Text = ...,
            relation: typing.Text = ...,
            subject: typing.Optional[ory.keto.acl.v1alpha1.acl_pb2.Subject] = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions.Literal["subject", b"subject"]
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal[
                "namespace",
                b"namespace",
                "object",
                b"object",
                "relation",
                b"relation",
                "subject",
                b"subject",
            ],
        ) -> None: ...

    QUERY_FIELD_NUMBER: builtins.int
    @property
    def query(self) -> global___DeleteRelationTuplesRequest.Query: ...
    def __init__(
        self,
        *,
        query: typing.Optional[global___DeleteRelationTuplesRequest.Query] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["query", b"query"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["query", b"query"]
    ) -> None: ...

global___DeleteRelationTuplesRequest = DeleteRelationTuplesRequest

class DeleteRelationTuplesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(
        self,
    ) -> None: ...

global___DeleteRelationTuplesResponse = DeleteRelationTuplesResponse
